require:
  - rubocop-airbnb

inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "lib/tasks/auto_annotate_models.rake"

Layout/LineLength:
  Max: 120
