require:
  - rubocop-airbnb
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-factory_bot

inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

inherit_gem:
  rswag-specs: .rubocop_rspec_alias_config.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "lib/tasks/auto_annotate_models.rake"

Layout/LineLength:
  Max: 120

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit
