---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    author_entity:
      type: object
      properties:
        id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
      required:
      - id
      - first_name
      - last_name
    error_message:
      type: object
      properties:
        name:
          type: string
        messages:
          type: array
          items:
            type: string
      required:
      - name
      - messages
    errors_resp:
      type: object
      properties:
        status:
          type: integer
        errors:
          type: array
          items:
            "$ref": "#/components/schemas/error_message"
      required:
      - status
      - errors
paths:
  "/v1/authors":
    post:
      summary: Creates a author
      tags:
      - Authors
      parameters: []
      responses:
        '201':
          description: created a new author
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 0617ff1f-294f-4c14-a56b-375097d3e810
                    first_name: Bob
                    last_name: Marley
              schema:
                "$ref": "#/components/schemas/author_entity"
        '400':
          description: invalid request
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 400
                    errors:
                      name: last_name
                      message: last_name is missing
              schema:
                "$ref": "#/components/schemas/errors_resp"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
              required:
              - first_name
              - last_name
            examples:
              author_create:
                summary: Successful create
                value:
                  first_name: Bob
                  last_name: Marley
              author_missing_params:
                summary: Validation error
                value:
                  first_name: Bob
servers:
- url: http://{defaultHost}/api
  variables:
    defaultHost:
      default: localhost:3000
