---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    author_entity:
      type: object
      properties:
        id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
      required:
      - id
      - first_name
      - last_name
    error_message:
      type: object
      properties:
        name:
          type: string
        messages:
          type: array
          items:
            type: string
      required:
      - name
      - messages
    errors_resp:
      type: object
      properties:
        status:
          type: integer
        errors:
          oneOf:
          - type: array
            items:
              type: string
          - type: array
            items:
              "$ref": "#/components/schemas/error_message"
      required:
      - status
      - errors
paths:
  "/v1/authors/{id}":
    get:
      summary: Get a author by id
      tags:
      - Authors
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: created a new author
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 3beedd93-b338-4283-84d9-fa7a2b5de335
                    first_name: Bob
                    last_name: Marley
              schema:
                "$ref": "#/components/schemas/author_entity"
        '400':
          description: invalid request
          content:
            application/json:
              examples:
                example:
                  value:
                    status: 400
                    errors:
                      name: last_name
                      message: last_name is missing
              schema:
                "$ref": "#/components/schemas/errors_resp"
servers:
- url: http://{defaultHost}/api
  variables:
    defaultHost:
      default: localhost:3000
